// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addfriends.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddFriendsRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserIDList           []string `protobuf:"bytes,2,rep,name=UserIDList,proto3" json:"UserIDList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendsRequest) Reset()         { *m = AddFriendsRequest{} }
func (m *AddFriendsRequest) String() string { return proto.CompactTextString(m) }
func (*AddFriendsRequest) ProtoMessage()    {}
func (*AddFriendsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28940ff5ae7b312b, []int{0}
}

func (m *AddFriendsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendsRequest.Unmarshal(m, b)
}
func (m *AddFriendsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendsRequest.Marshal(b, m, deterministic)
}
func (m *AddFriendsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendsRequest.Merge(m, src)
}
func (m *AddFriendsRequest) XXX_Size() int {
	return xxx_messageInfo_AddFriendsRequest.Size(m)
}
func (m *AddFriendsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendsRequest proto.InternalMessageInfo

func (m *AddFriendsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AddFriendsRequest) GetUserIDList() []string {
	if m != nil {
		return m.UserIDList
	}
	return nil
}

type AddFriendsResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendsResponse) Reset()         { *m = AddFriendsResponse{} }
func (m *AddFriendsResponse) String() string { return proto.CompactTextString(m) }
func (*AddFriendsResponse) ProtoMessage()    {}
func (*AddFriendsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28940ff5ae7b312b, []int{1}
}

func (m *AddFriendsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendsResponse.Unmarshal(m, b)
}
func (m *AddFriendsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendsResponse.Marshal(b, m, deterministic)
}
func (m *AddFriendsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendsResponse.Merge(m, src)
}
func (m *AddFriendsResponse) XXX_Size() int {
	return xxx_messageInfo_AddFriendsResponse.Size(m)
}
func (m *AddFriendsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendsResponse proto.InternalMessageInfo

func (m *AddFriendsResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*AddFriendsRequest)(nil), "pb.AddFriendsRequest")
	proto.RegisterType((*AddFriendsResponse)(nil), "pb.AddFriendsResponse")
}

func init() { proto.RegisterFile("addfriends.proto", fileDescriptor_28940ff5ae7b312b) }

var fileDescriptor_28940ff5ae7b312b = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4c, 0x49, 0x49,
	0x2b, 0xca, 0x4c, 0xcd, 0x4b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x92, 0xe2, 0x29, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x81, 0x88, 0x28, 0x79, 0x73, 0x09, 0x3a, 0xa6,
	0xa4, 0xb8, 0x41, 0x54, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x71, 0xb1, 0x85,
	0x16, 0xa7, 0x16, 0x79, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42, 0x72,
	0x5c, 0x5c, 0x10, 0x96, 0x4f, 0x66, 0x71, 0x89, 0x04, 0x93, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x92,
	0x88, 0x92, 0x05, 0x97, 0x10, 0xb2, 0x61, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x4a, 0x5c,
	0x6c, 0x41, 0x60, 0x2b, 0xc1, 0xa6, 0x71, 0x1b, 0x71, 0xe9, 0x15, 0x24, 0xe9, 0x41, 0x44, 0x82,
	0xa0, 0x32, 0x4e, 0xac, 0xab, 0x98, 0x98, 0x0a, 0x92, 0x92, 0xd8, 0xc0, 0x8e, 0x32, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x49, 0xcb, 0xd1, 0x4f, 0xba, 0x00, 0x00, 0x00,
}
