// Code generated by protoc-gen-go. DO NOT EDIT.
// source: changestatus.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChangeStatusRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeStatusRequest) Reset()         { *m = ChangeStatusRequest{} }
func (m *ChangeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeStatusRequest) ProtoMessage()    {}
func (*ChangeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fa6f09d7c78d01c, []int{0}
}

func (m *ChangeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatusRequest.Unmarshal(m, b)
}
func (m *ChangeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatusRequest.Marshal(b, m, deterministic)
}
func (m *ChangeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatusRequest.Merge(m, src)
}
func (m *ChangeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeStatusRequest.Size(m)
}
func (m *ChangeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatusRequest proto.InternalMessageInfo

func (m *ChangeStatusRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ChangeStatusRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ChangeStatusNotice struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeStatusNotice) Reset()         { *m = ChangeStatusNotice{} }
func (m *ChangeStatusNotice) String() string { return proto.CompactTextString(m) }
func (*ChangeStatusNotice) ProtoMessage()    {}
func (*ChangeStatusNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fa6f09d7c78d01c, []int{1}
}

func (m *ChangeStatusNotice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatusNotice.Unmarshal(m, b)
}
func (m *ChangeStatusNotice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatusNotice.Marshal(b, m, deterministic)
}
func (m *ChangeStatusNotice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatusNotice.Merge(m, src)
}
func (m *ChangeStatusNotice) XXX_Size() int {
	return xxx_messageInfo_ChangeStatusNotice.Size(m)
}
func (m *ChangeStatusNotice) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatusNotice.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatusNotice proto.InternalMessageInfo

func (m *ChangeStatusNotice) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ChangeStatusNotice) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*ChangeStatusRequest)(nil), "pb.ChangeStatusRequest")
	proto.RegisterType((*ChangeStatusNotice)(nil), "pb.ChangeStatusNotice")
}

func init() { proto.RegisterFile("changestatus.proto", fileDescriptor_2fa6f09d7c78d01c) }

var fileDescriptor_2fa6f09d7c78d01c = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0x48, 0xcc,
	0x4b, 0x4f, 0x2d, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2a, 0x48, 0x52, 0x72, 0xe5, 0x12, 0x76, 0x06, 0xcb, 0x04, 0x83, 0x65, 0x82, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x84, 0xc4, 0xb8, 0xd8, 0x42, 0x8b, 0x53, 0x8b, 0x3c, 0x5d, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x90, 0x38, 0x44, 0xa1, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b,
	0x10, 0x94, 0xa7, 0xe4, 0xc2, 0x25, 0x84, 0x6c, 0x8c, 0x5f, 0x7e, 0x49, 0x66, 0x72, 0x2a, 0xa9,
	0xa6, 0x38, 0xb1, 0xae, 0x62, 0x62, 0x2a, 0x48, 0x4a, 0x62, 0x03, 0x3b, 0xcf, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x22, 0x8e, 0x06, 0x30, 0xb4, 0x00, 0x00, 0x00,
}
