// Code generated by protoc-gen-go. DO NOT EDIT.
// source: friendchat.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FriendChatRequest struct {
	FromUserID           string   `protobuf:"bytes,1,opt,name=FromUserID,proto3" json:"FromUserID,omitempty"`
	ToUserID             string   `protobuf:"bytes,2,opt,name=ToUserID,proto3" json:"ToUserID,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendChatRequest) Reset()         { *m = FriendChatRequest{} }
func (m *FriendChatRequest) String() string { return proto.CompactTextString(m) }
func (*FriendChatRequest) ProtoMessage()    {}
func (*FriendChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f25b3341134742e5, []int{0}
}

func (m *FriendChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendChatRequest.Unmarshal(m, b)
}
func (m *FriendChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendChatRequest.Marshal(b, m, deterministic)
}
func (m *FriendChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendChatRequest.Merge(m, src)
}
func (m *FriendChatRequest) XXX_Size() int {
	return xxx_messageInfo_FriendChatRequest.Size(m)
}
func (m *FriendChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FriendChatRequest proto.InternalMessageInfo

func (m *FriendChatRequest) GetFromUserID() string {
	if m != nil {
		return m.FromUserID
	}
	return ""
}

func (m *FriendChatRequest) GetToUserID() string {
	if m != nil {
		return m.ToUserID
	}
	return ""
}

func (m *FriendChatRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type FriendChatNotice struct {
	FromUserID           string   `protobuf:"bytes,1,opt,name=FromUserID,proto3" json:"FromUserID,omitempty"`
	ToUserID             string   `protobuf:"bytes,2,opt,name=ToUserID,proto3" json:"ToUserID,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendChatNotice) Reset()         { *m = FriendChatNotice{} }
func (m *FriendChatNotice) String() string { return proto.CompactTextString(m) }
func (*FriendChatNotice) ProtoMessage()    {}
func (*FriendChatNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor_f25b3341134742e5, []int{1}
}

func (m *FriendChatNotice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendChatNotice.Unmarshal(m, b)
}
func (m *FriendChatNotice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendChatNotice.Marshal(b, m, deterministic)
}
func (m *FriendChatNotice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendChatNotice.Merge(m, src)
}
func (m *FriendChatNotice) XXX_Size() int {
	return xxx_messageInfo_FriendChatNotice.Size(m)
}
func (m *FriendChatNotice) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendChatNotice.DiscardUnknown(m)
}

var xxx_messageInfo_FriendChatNotice proto.InternalMessageInfo

func (m *FriendChatNotice) GetFromUserID() string {
	if m != nil {
		return m.FromUserID
	}
	return ""
}

func (m *FriendChatNotice) GetToUserID() string {
	if m != nil {
		return m.ToUserID
	}
	return ""
}

func (m *FriendChatNotice) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*FriendChatRequest)(nil), "pb.FriendChatRequest")
	proto.RegisterType((*FriendChatNotice)(nil), "pb.FriendChatNotice")
}

func init() { proto.RegisterFile("friendchat.proto", fileDescriptor_f25b3341134742e5) }

var fileDescriptor_f25b3341134742e5 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2b, 0xca, 0x4c,
	0xcd, 0x4b, 0x49, 0xce, 0x48, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0xca, 0xe4, 0x12, 0x74, 0x03, 0x8b, 0x3b, 0x67, 0x24, 0x96, 0x04, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0xc9, 0x71, 0x71, 0xb9, 0x15, 0xe5, 0xe7, 0x86, 0x16, 0xa7, 0x16, 0x79, 0xba,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x89, 0x08, 0x49, 0x71, 0x71, 0x84, 0xe4, 0x43,
	0x65, 0x99, 0xc0, 0xb2, 0x70, 0xbe, 0x90, 0x04, 0x17, 0xbb, 0x73, 0x7e, 0x5e, 0x49, 0x6a, 0x5e,
	0x89, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x8c, 0xab, 0x94, 0xc1, 0x25, 0x80, 0xb0, 0xca,
	0x2f, 0xbf, 0x24, 0x33, 0x39, 0x95, 0x36, 0x36, 0x39, 0xb1, 0xae, 0x62, 0x62, 0x2a, 0x48, 0x4a,
	0x62, 0x03, 0x7b, 0xd3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x3b, 0x75, 0xc7, 0xfa, 0x00,
	0x00, 0x00,
}
