// Code generated by protoc-gen-go. DO NOT EDIT.
// source: getfriends.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetFriendsRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendsRequest) Reset()         { *m = GetFriendsRequest{} }
func (m *GetFriendsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFriendsRequest) ProtoMessage()    {}
func (*GetFriendsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97252f636d9847b5, []int{0}
}

func (m *GetFriendsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendsRequest.Unmarshal(m, b)
}
func (m *GetFriendsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendsRequest.Marshal(b, m, deterministic)
}
func (m *GetFriendsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsRequest.Merge(m, src)
}
func (m *GetFriendsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFriendsRequest.Size(m)
}
func (m *GetFriendsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsRequest proto.InternalMessageInfo

func (m *GetFriendsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetFriendsResponse struct {
	Result               *Result     `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Friends              []*UserInfo `protobuf:"bytes,2,rep,name=Friends,proto3" json:"Friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetFriendsResponse) Reset()         { *m = GetFriendsResponse{} }
func (m *GetFriendsResponse) String() string { return proto.CompactTextString(m) }
func (*GetFriendsResponse) ProtoMessage()    {}
func (*GetFriendsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97252f636d9847b5, []int{1}
}

func (m *GetFriendsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendsResponse.Unmarshal(m, b)
}
func (m *GetFriendsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendsResponse.Marshal(b, m, deterministic)
}
func (m *GetFriendsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsResponse.Merge(m, src)
}
func (m *GetFriendsResponse) XXX_Size() int {
	return xxx_messageInfo_GetFriendsResponse.Size(m)
}
func (m *GetFriendsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsResponse proto.InternalMessageInfo

func (m *GetFriendsResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetFriendsResponse) GetFriends() []*UserInfo {
	if m != nil {
		return m.Friends
	}
	return nil
}

func init() {
	proto.RegisterType((*GetFriendsRequest)(nil), "pb.GetFriendsRequest")
	proto.RegisterType((*GetFriendsResponse)(nil), "pb.GetFriendsResponse")
}

func init() { proto.RegisterFile("getfriends.proto", fileDescriptor_97252f636d9847b5) }

var fileDescriptor_97252f636d9847b5 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4f, 0x2d, 0x49,
	0x2b, 0xca, 0x4c, 0xcd, 0x4b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x92, 0xe2, 0x29, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x81, 0x88, 0x48, 0xf1, 0x95, 0x16, 0xa7, 0x16,
	0x65, 0xe6, 0xa5, 0xe5, 0x43, 0xf8, 0x4a, 0xda, 0x5c, 0x82, 0xee, 0xa9, 0x25, 0x6e, 0x10, 0x5d,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x62, 0x5c, 0x6c, 0xa1, 0xc5, 0xa9, 0x45, 0x9e,
	0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x52, 0x02, 0x97, 0x10, 0xb2, 0xe2,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x25, 0x2e, 0xb6, 0x20, 0xb0, 0x15, 0x60, 0xd5, 0xdc,
	0x46, 0x5c, 0x7a, 0x05, 0x49, 0x7a, 0x10, 0x91, 0x20, 0xa8, 0x8c, 0x90, 0x1a, 0x17, 0x3b, 0x54,
	0x9b, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0x0f, 0x48, 0x11, 0xd8, 0xd8, 0xbc, 0xb4, 0xfc,
	0x20, 0x98, 0xa4, 0x13, 0xeb, 0x2a, 0x26, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0xe3, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x29, 0x30, 0x21, 0x22, 0xd2, 0x00, 0x00, 0x00,
}
