// Code generated by protoc-gen-go. DO NOT EDIT.
// source: updateuserinfo.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateUserInfoRequest struct {
	User                 *UserInfo `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateUserInfoRequest) Reset()         { *m = UpdateUserInfoRequest{} }
func (m *UpdateUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfoRequest) ProtoMessage()    {}
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a4b0c754d7f2dff, []int{0}
}

func (m *UpdateUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfoRequest.Unmarshal(m, b)
}
func (m *UpdateUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfoRequest.Merge(m, src)
}
func (m *UpdateUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfoRequest.Size(m)
}
func (m *UpdateUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfoRequest proto.InternalMessageInfo

func (m *UpdateUserInfoRequest) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateUserInfoRequest)(nil), "pb.UpdateUserInfoRequest")
}

func init() { proto.RegisterFile("updateuserinfo.proto", fileDescriptor_0a4b0c754d7f2dff) }

var fileDescriptor_0a4b0c754d7f2dff = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x2d, 0x48, 0x49,
	0x2c, 0x49, 0x2d, 0x2d, 0x4e, 0x2d, 0xca, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0x48, 0x92, 0xe2, 0x43, 0x15, 0x53, 0xb2, 0xe4, 0x12, 0x0d, 0x05, 0xab, 0x0d,
	0x2d, 0x4e, 0x2d, 0xf2, 0xcc, 0x4b, 0xcb, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52,
	0xe0, 0x62, 0x01, 0x09, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe8, 0x15, 0x24, 0xe9,
	0xc1, 0x95, 0x80, 0x65, 0x9c, 0x58, 0x57, 0x31, 0x31, 0x15, 0x24, 0x25, 0xb1, 0x81, 0x0d, 0x32,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x41, 0x69, 0x18, 0x9b, 0x74, 0x00, 0x00, 0x00,
}
